version: '2'

networks:
  bridge:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: spotify-mongodb
    environment:
      -  'MONGO_INITDB_ROOT_USERNAME=root' 
      -  'MONGO_INITDB_ROOT_PASSWORD=root!'
      -  'TZ=Asia/Tokyo'
    volumes:
      - 'mongodb-data:/data/db'
      - ./docker-entrypoint-initdb.d/1-mongo-init.js:/docker-entrypoint-initdb.d/1-mongo-init.js:ro
    ports:
      - '27017:27017'
    # command: mongod --smallfiles
    command: mongod --auth
  mongo-express:
    container_name: spotify-mongo-express
    links:
      - 'mongodb:mongo'
    ports:
      - '8081:8081'
    environment:
      - 'ME_CONFIG_OPTIONS_EDITORTHEME=ambiance'
      - 'ME_CONFIG_MONGODB_ENABLE_ADMIN="false"'
      - 'ME_CONFIG_MONGODB_AUTH_DATABASE=admin'
      - 'ME_CONFIG_MONGODB_AUTH_USERNAME=root'
      - 'ME_CONFIG_MONGODB_AUTH_PASSWORD=root!'
      - 'ME_CONFIG_BASICAUTH_USERNAME=user'
      - 'ME_CONFIG_BASICAUTH_PASSWORD=password!'
    image: mongo-express

volumes:
  mongodb-data: {}
