version: '2'

networks:
  bridge:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: spotify-mongodb
    environment:
      -  'MONGO_INITDB_ROOT_USERNAME=root' 
      -  'MONGO_INITDB_ROOT_PASSWORD=root!'
      -  'TZ=Asia/Tokyo'
    volumes:
      - 'mongodb-data:/data/db'
      - ./docker-entrypoint-initdb.d/1-mongo-init.js:/docker-entrypoint-initdb.d/1-mongo-init.js:ro
    ports:
      - '27017:27017'
    # command: mongod --smallfiles
    command: mongod --auth

volumes:
  mongodb-data: {}
